### ISSUE TITLE
errors even with allRules: false

### ISSUE THREAD

**Issue by gemal** [phpstan/phpstan-strict-rules#185]
I just updated to strict v1.4.0 and I added:

```
includes:
    - vendor/phpstan/phpstan-strict-rules/rules.neon
parameters:
    strictRules:
        allRules: false
```

but now I'm getting this:

`Variable property access on $this(App\Controller\AppController).`

is this correct? I thought that `allRules: false` disabled all strict rules

**Comment by ondrejmirtes** [comment]
Can you please post the code sample that reports this?

/cc @MartinMystikJonas

**Comment by gemal** [comment]
`$this->{$model}->localeDetails['Country'] = $country['Country'];`

doesn't `allRules: false` disable all the strict rules?

**Comment by ondrejmirtes** [comment]
Yeah, it should, there's gonna be some misconfiguration that should be obvious by looking at rules.neon.

**Comment by MartinMystikJonas** [comment]
I will check it

**Comment by gemal** [comment]
perhaps I dont understand the documentation
I used to have this in the phpstan.neon
```
services:
    -
        class: PHPStan\Rules\SwitchConditions\MatchingTypeInSwitchCaseConditionRule
        tags:
            - phpstan.rules.rule
```

then I updated strict and deleted it and replaced it with:
```
includes:
    - vendor/phpstan/phpstan-strict-rules/rules.neon
parameters:
    strictRules:
        allRules: false
```

and now all kind of errors
